name: Check CUNY Classes

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  check_classes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # You can adjust the Python version if needed

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run class check script
        env:
          CUNY_USERNAME: ${{ secrets.CUNY_USERNAME }}
          CUNY_PASSWORD: ${{ secrets.CUNY_PASSWORD }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COURSE_NAMES: ${{ secrets.COURSE_NAMES }}
          COURSE_CODES: ${{ secrets.COURSE_CODES }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
        run: python check.py 